config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :drafts, on: :collection
    get :pending, on: :collection
    patch :publish, on: :member
    patch :unpublish, on: :member
    resources :comments, shallow: true
    resources :subscriptions_posts, shallow: true, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
    resources :posts, only: [] do
      patch :approve, on: :member
      patch :reject, on: :member
      get :pending, on: :collection
    end
    get 'welcome', to: 'welcome#index'
  end

  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categories_posts
  has_many :posts, through: :categories_posts

  validates :name, presence: true, uniqueness: { case_sensitive: false }


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: t('admin.categories.notices.new_category')
      else
        render :new
      end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: t('admin.categories.notices.category_update')
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, notice: t('admin.categories.notices.remove')
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = @category.posts.approved.all
    render 'posts/index'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
    <%= render 'common/errors', object: @category %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_area :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t('.editing') %></h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1><%= t('.list') %></h1>

<div class="container col-md-6">
    <table class="table table-condensed">
      <thead>
      <tr>
        <th><%= t('activerecord.attributes.category.name') %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to t('common.edit'), edit_admin_category_path(category) %></td>
            <td><%= link_to t('common.delete'), [:admin, category], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <hr>

    <%= link_to t('.new'), new_admin_category_path %>

</div>

app/views/admin/categories/new.html.erb
<h1><%= t('admin.categories.index.new') %></h1>

<%= render 'form' %>