config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :drafts, on: :collection
    get :pending, on: :collection
    patch :publish, on: :member
    patch :unpublish, on: :member
    resources :comments, shallow: true
    resources :subscriptions_posts, shallow: true, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
    resources :posts, only: [] do
      patch :approve, on: :member
      patch :reject, on: :member
      get :pending, on: :collection
    end
    get 'welcome', to: 'welcome#index'
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  enum status: [ :draft, :pending, :approved ]

  has_many :categories_posts
  has_many :categories, through: :categories_posts
  has_many :comments, dependent: :destroy
  has_many :tags_posts
  has_many :tags, through: :tags_posts
  has_many :subscriptions_posts
  has_many :subscribers, through: :subscriptions_posts, source: :user
  belongs_to :user

  validates :title, :body, :user_id, presence: true

  scope :approved, -> { where(status: 2) }
  scope :draft, -> { where(status: 0) }
  scope :pending, -> { where(status: 1) }

  after_create :subscribe_author

  private

  def subscribe_author

    user.subscribe_to(self)

  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_action :set_post, only: [:reject, :approve]

  def pending
      @posts = Post.pending.all
  end

  def reject
    @post.draft!
    NotificationMailer.post_rejected_notification(@post).deliver_now
    redirect_to pending_admin_posts_url, notice: t('admin.posts.rejected')
  end

  def approve
    @post.approved!
    NotificationMailer.post_approved_notification(@post).deliver_now
    redirect_to pending_admin_posts_url, notice: t('admin.posts.approved')
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  before_action :check_owner, only: [:edit, :update, :destroy, :publish, :unpublish]

  # GET /posts
  def index
    @posts = Post.approved.all
  end

  def drafts
    unless current_user.admin?
      @posts = Post.draft.where(user_id: current_user.id)
    else
      @posts = Post.draft.all
    end
  end

  def pending
      @posts = Post.pending.where(user_id: current_user.id)
  end

  def publish
    @post.pending!
    redirect_to posts_url, notice: t('posts.notices.submit_to_moderator')
  end

  def unpublish
    @post.draft!
    redirect_to drafts_posts_url, notice: t('posts.notices.moved_to_drafts')
  end

  # GET /posts/1
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: t('posts.notices.created')
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      @post.draft!
      redirect_to @post, notice: t('posts.notices.updated')
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: t('posts.notices.destroyed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def check_owner
      unless current_user.owner_of?(@post)
        redirect_to posts_path, alert: t('common.not_enough_rights')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<% if user_signed_in? %>
    <% unless @post.comments.empty? %>
        <strong><%= t('common.comments')+' ('+@post.comments.count.to_s+')'%></strong>
        <% @post.comments.each do |comment| %>
            <% if comment.user.present? %>
                <p>
                  <strong><%= t('.author')%>:</strong>
                  <%= comment.user.email %>
                </p>
            <% end %>
            <p><%= comment.body %></p>
            <% if user_signed_in? && current_user.owner_of?(comment) %>
                <p>
                  <%= link_to t('common.delete'), comment, method: :delete, data: { confirm: t('common.confirm') } %> |
                  <%= link_to t('common.edit'), edit_comment_path(comment) %>
                </p>
            <% end %>
        <% end %>
        <strong><%= t('common.new_comment') %></strong>
    <% else %>
        <strong><%= t('.no_comments')+' '+t('.leave_first_comment') %></strong>
        <br>
    <% end %>

    <%= render 'comments/form' %>

<% else %>

    <% unless @post.comments.empty? %>
        <strong><%=t('common.comments')+' ('+@post.comments.count.to_s+')'%></strong>
        <% @post.comments.each do |comment| %>
            <% if comment.user.present? %>
                <p>
                  <strong><%= t('.author')%></strong>
                  <%= comment.user.email %>
                </p>
            <% end %>
            <p><%= comment.body %></p>
            <% if user_signed_in? && current_user.owner_of?(comment) %>
                <p>
                  <%= link_to t('common.delete'), comment, method: :delete, data: { confirm: t('common.confirm') } %> |
                  <%= link_to t('common.edit'), edit_comment_path(comment) %>
                </p>
            <% end %>
        <% end %>
    <% else%>
        <strong><%= t('.no_comments')%></strong>
        <br>
    <% end %>

<% end %>

app/views/posts/_editlinks.html.erb
<% if user_signed_in? %>

    <% if current_user.subscribed_to?(post) %>
        <%= link_with_icon 'square-o', current_user.subscription_for(post), method: :delete %>
    <% else %>
        <%= link_with_icon 'check-square-o', post_subscriptions_posts_path(post), method: :post %>
    <% end %>

    <% if current_user.owner_of?(post) %>
        <%= link_with_icon 'pencil-square-o', edit_post_path(post) %>
        <%= link_with_icon 'trash-o', post, method: :delete, data: { confirm: t('common.confirm') } %>
        <%if post.approved? %>
            <%= link_to t('.move_to_drafts'), unpublish_post_path(post.id), method: :patch %>
        <% elsif post.draft? %>
            <%= link_to t('.send_for_moderation'), publish_post_path(post.id), method: :patch %>
        <% end %>
    <% end %>

<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'common/errors', object: @post %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_ids, t('.categories') %><br>
    <%= f.collection_select :category_ids, Category.all, :id, :name, {}, {multiple: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="container col-lg-12">
  <div class="row">
    <h2><%= link_to post.title, post %></h2>
  </div>

    <%= render post.categories %>

  <div class="row">
    <p><%= truncate(post.body, length: 100) %></p>
    <p><%= link_to 'Читать далее', post %></p>
    <%= render 'editlinks', post: post %>

  </div>

  <hr>

</div>

app/views/posts/drafts.html.erb
<h1><%= t('.drafts') %></h1>

<% if @posts %>
    <%= render @posts %>
<% end %>

app/views/posts/edit.html.erb
<h1><%= t('.editing') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>
  <% if @category %>
      <%= t('.title_w_category')+' '+@category.name %>
  <% else %>
      <%= t('.title') %>
  <% end %>
</h1>

<% if @posts %>
    <%= render @posts %>
<% end %>

<br>

<%= link_to t('common.new_post'), new_post_path, class: 'btn btn-large' if user_signed_in?  %>

app/views/posts/new.html.erb
<h1><%= t('.new') %></h1>

<%= render 'form' %>

app/views/posts/pending.html.erb
<h1><%= t('.list_of_pending') %></h1>

<% if @posts %>
    <%= render @posts %>
<% end %>

<br>

app/views/posts/show.html.erb
<h2> <%= @post.title %></h2>
<%= render @post.categories %>

<% if @post.user.present? %>
    <p>
      <strong><%= t('common.author') %></strong>
      <%= @post.user.email %>
    </p>
<% end %>
<p>
  <%= @post.body %>
</p>

<%= render 'comments' %>

<%= render 'editlinks', post: @post %>