config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :drafts, on: :collection
    get :pending, on: :collection
    patch :publish, on: :member
    patch :unpublish, on: :member
    resources :comments, shallow: true
    resources :subscriptions_posts, shallow: true, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
    resources :posts, only: [] do
      patch :approve, on: :member
      patch :reject, on: :member
      get :pending, on: :collection
    end
    get 'welcome', to: 'welcome#index'
  end

  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categories_posts
  has_many :posts, through: :categories_posts

  validates :name, presence: true, uniqueness: { case_sensitive: false }


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: t('admin.categories.notices.new_category')
      else
        render :new
      end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: t('admin.categories.notices.category_update')
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, notice: t('admin.categories.notices.remove')
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = @category.posts.approved.all
    render 'posts/index'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

end

app/views/categories/_category.html.erb
<small><%= category.name+', ' %></small>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <%= render 'common/errors', object: @category %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_area :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/categories/_indexlink.html.erb
<ul class="nav">
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category %></li>
    <% end %>
    <hr>
    <li><%= link_to t('.all_categories'), posts_path %></li>
</ul>

app/views/categories/edit.html.erb
<h1>Редактируем категорию</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>