config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :drafts, on: :collection
    get :pending, on: :collection
    patch :publish, on: :member
    patch :unpublish, on: :member
    resources :comments, shallow: true
    resources :subscriptions_posts, shallow: true, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
    resources :posts, only: [] do
      patch :approve, on: :member
      patch :reject, on: :member
      get :pending, on: :collection
    end
    get 'welcome', to: 'welcome#index'
  end

  root 'posts#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SbHabr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SbHabr</a>
        <div class="col-lg-9 navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to t('.admin'), admin_welcome_path %></li>
                <li><%= link_to t('.categories'), admin_categories_path %></li>
                <li><%= link_to t('.users'), admin_users_path %></li>
                <li><%= link_to t('.moderator'), pending_admin_posts_path %></li>
              </ul>
        </div>
        <div class="col-lg-3 col-lg-push- navbar-collapse collapse navbar-responsive-collapse">
            <% if user_signed_in? %>
                 <ul class="nav navbar-nav">
                     <li><%= link_to current_user.email, destroy_user_session_path, method: :delete %></li>
                     <li><%= link_to t('common.logout'), destroy_user_session_path, method: :delete  %></li>
                 </ul>
            <% else %>
                 <ul class="nav navbar-nav">
                     <li><%= link_to t('common.login'), new_user_session_path %></li>
                 </ul>
            <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; 2015 Степан Большаков</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SbHabr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SbHabr</a>
        <div class="col-lg-9 navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to t('.list_of_posts'), posts_path %></li>
            <li><%= link_to t('.list_of_drafts'), drafts_posts_path %></li>
            <li><%= link_to t('.list_of_pending'), pending_posts_path %></li>
            <% if user_signed_in? && current_user.admin? %>
                <li><%= link_to t('.admin'), admin_welcome_path %>
            <% end %>
          </ul>

        </div>
        <div class="col-lg-3 col-lg-push-2 navbar-collapse collapse navbar-responsive-collapse">
            <% if user_signed_in? %>
                 <ul class="nav navbar-nav">
                     <li><%= link_to current_user.email, destroy_user_session_path, method: :delete %></li>
                     <li><%= link_to t('common.logout'), destroy_user_session_path, method: :delete  %></li>
                 </ul>
            <% else %>
                 <ul class="nav navbar-nav">
                     <li><%= link_to t('common.login'), new_user_session_path %></li>
                 </ul>
            <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3><%= t('.list_of_categories') %></h3>
            <%= render "categories/indexlink" %>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; 2015 Степан Большаков</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>